import { describe, expect, test } from "bun:test";
import { generateManifestDts } from "@/manifest-codegen";
import type { ParsedAction } from "@/manifest-codegen";

describe("generateManifestDts", () => {
  test("returns empty string for no actions", () => {
    expect(generateManifestDts([])).toBe("");
  });

  test("generates correct module augmentation for single action", () => {
    const actions: ParsedAction[] = [{ uuid: "com.example.counter", controllers: ["Keypad"] }];

    const result = generateManifestDts(actions);

    expect(result).toContain('import "@fcannizzaro/streamdeck-react"');
    expect(result).toContain('declare module "@fcannizzaro/streamdeck-react"');
    expect(result).toContain("interface ManifestActions");
    expect(result).toContain('"com.example.counter"');
    expect(result).toContain('readonly ["Keypad"]');
  });

  test("generates correct output for multiple actions", () => {
    const actions: ParsedAction[] = [
      { uuid: "com.example.counter", controllers: ["Keypad"] },
      { uuid: "com.example.volume", controllers: ["Keypad", "Encoder"] },
    ];

    const result = generateManifestDts(actions);

    expect(result).toContain('"com.example.counter"');
    expect(result).toContain('"com.example.volume"');
    expect(result).toContain('readonly ["Keypad"]');
    expect(result).toContain('readonly ["Keypad", "Encoder"]');
  });

  test("generates correct output for encoder-only action", () => {
    const actions: ParsedAction[] = [{ uuid: "com.example.dial", controllers: ["Encoder"] }];

    const result = generateManifestDts(actions);

    expect(result).toContain('readonly ["Encoder"]');
  });

  test("includes auto-generated header comment", () => {
    const actions: ParsedAction[] = [{ uuid: "com.example.test", controllers: ["Keypad"] }];

    const result = generateManifestDts(actions);

    expect(result).toContain("auto-generated by @fcannizzaro/streamdeck-react");
    expect(result).toContain("Do not edit this file manually");
  });

  test("output is valid TypeScript structure", () => {
    const actions: ParsedAction[] = [
      { uuid: "com.example.a", controllers: ["Keypad"] },
      { uuid: "com.example.b", controllers: ["Encoder"] },
    ];

    const result = generateManifestDts(actions);

    // Verify basic structure
    const lines = result.split("\n");
    expect(lines.some((l) => l.includes("interface ManifestActions"))).toBe(true);
    // Opening and closing braces should be balanced
    const opens = (result.match(/{/g) || []).length;
    const closes = (result.match(/}/g) || []).length;
    expect(opens).toBe(closes);
  });
});
