import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

// ── Manifest → TypeScript DTS Codegen ───────────────────────────────
//
// Reads the plugin's manifest.json and generates a TypeScript
// declaration file (streamdeck-env.d.ts) that augments the
// ManifestActions interface from types.ts.
//
// Pipeline:
//
//   manifest.json
//     ↓ findManifestPath() — auto-detect *.sdPlugin/manifest.json
//     ↓ parseManifest() — extract UUID + Controllers per action
//     ↓ generateManifestDts() — emit `declare module` augmentation
//     ↓ writeManifestDtsIfChanged() — skip write if content unchanged
//     ↓
//   src/streamdeck-env.d.ts
//
// Generated output example:
//
//   declare module "@fcannizzaro/streamdeck-react" {
//     interface ManifestActions {
//       "com.example.counter": {
//         controllers: readonly ["Keypad"];
//       };
//       "com.example.dial": {
//         controllers: readonly ["Encoder"];
//       };
//     }
//   }
//
// This enables type-safe defineAction() — see types.ts for how
// ManifestActions drives the conditional type machinery.
//
// writeManifestDtsIfChanged skips the write when content is identical.
// This prevents unnecessary TypeScript recompilation and HMR triggers
// during watch mode when the manifest hasn't actually changed.

// ── Manifest Parsing ────────────────────────────────────────────────

interface ManifestAction {
  UUID: string;
  Controllers?: ("Keypad" | "Encoder")[];
}

interface Manifest {
  Actions?: ManifestAction[];
}

export interface ParsedAction {
  uuid: string;
  controllers: readonly ("Keypad" | "Encoder")[];
}

/**
 * Find the manifest.json inside a `*.sdPlugin` directory.
 *
 * - If `explicit` is a string, it is resolved against `root`.
 * - If `explicit` is `false`, codegen is disabled (returns `null`).
 * - Otherwise, auto-detects by scanning `root` for `*.sdPlugin/manifest.json`.
 */
export function findManifestPath(
  root: string,
  explicit?: string | false,
  warn?: (msg: string) => void,
): string | null {
  if (explicit === false) return null;

  if (typeof explicit === "string") {
    const resolved = resolve(root, explicit);
    if (!existsSync(resolved)) {
      warn?.(`[@fcannizzaro/streamdeck-react] Manifest not found at ${resolved}`);
      return null;
    }
    return resolved;
  }

  // Auto-detect: look for *.sdPlugin/manifest.json in root
  const entries = readdirSync(root, { withFileTypes: true });
  const sdPluginDirs = entries.filter(
    (entry) => entry.isDirectory() && entry.name.endsWith(".sdPlugin"),
  );

  if (sdPluginDirs.length === 0) return null;

  if (sdPluginDirs.length > 1) {
    warn?.(
      `[@fcannizzaro/streamdeck-react] Multiple .sdPlugin directories found. ` +
        `Using "${sdPluginDirs[0].name}". Set the \`manifest\` option to specify one explicitly.`,
    );
  }

  const manifestPath = join(root, sdPluginDirs[0].name, "manifest.json");
  return existsSync(manifestPath) ? manifestPath : null;
}

/**
 * Parse a Stream Deck plugin manifest and extract action metadata.
 * Returns an empty array on failure (with a warning).
 */
export function parseManifest(path: string, warn?: (msg: string) => void): ParsedAction[] {
  try {
    const content = readFileSync(path, "utf-8");
    const manifest: Manifest = JSON.parse(content);

    if (!Array.isArray(manifest.Actions)) {
      warn?.(`[@fcannizzaro/streamdeck-react] manifest.json has no Actions array`);
      return [];
    }

    const actions: ParsedAction[] = [];

    for (const action of manifest.Actions) {
      if (!action.UUID) {
        warn?.(`[@fcannizzaro/streamdeck-react] Skipping manifest action with missing UUID`);
        continue;
      }

      actions.push({
        uuid: action.UUID,
        controllers: action.Controllers ?? ["Keypad"],
      });
    }

    return actions;
  } catch (err) {
    warn?.(
      `[@fcannizzaro/streamdeck-react] Failed to parse manifest: ${err instanceof Error ? err.message : String(err)}`,
    );
    return [];
  }
}

// ── Code Generation ─────────────────────────────────────────────────

const HEADER = [
  "// This file is auto-generated by @fcannizzaro/streamdeck-react",
  "// Do not edit this file manually. It is regenerated from the plugin manifest.",
].join("\n");

/**
 * Generate the `declare module` augmentation string from parsed actions.
 * Returns an empty string when there are no actions.
 */
export function generateManifestDts(actions: ParsedAction[]): string {
  if (actions.length === 0) return "";

  const entries = actions.map((action) => {
    const controllers = action.controllers.map((c) => `"${c}"`).join(", ");
    return `    "${action.uuid}": {\n      controllers: readonly [${controllers}];\n    };`;
  });

  return [
    HEADER,
    "",
    'import "@fcannizzaro/streamdeck-react";',
    "",
    'declare module "@fcannizzaro/streamdeck-react" {',
    "  interface ManifestActions {",
    ...entries,
    "  }",
    "}",
    "",
  ].join("\n");
}

/**
 * Write the generated `.d.ts` file only when the content has changed.
 * Creates the parent directory if it does not exist.
 *
 * @returns `true` if the file was written, `false` if content was unchanged.
 */
export function writeManifestDtsIfChanged(outPath: string, content: string): boolean {
  if (content === "") return false;

  if (existsSync(outPath)) {
    const existing = readFileSync(outPath, "utf-8");
    if (existing === content) return false;
  }

  const dir = dirname(outPath);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  writeFileSync(outPath, content);
  return true;
}

/**
 * High-level helper: find, parse, generate, and write manifest types.
 *
 * @returns The resolved manifest path (for watch registration), or `null`.
 */
export function generateManifestTypes(
  root: string,
  manifestOption: string | false | undefined,
  warn?: (msg: string) => void,
): { manifestPath: string; written: boolean } | null {
  const manifestPath = findManifestPath(root, manifestOption, warn);
  if (!manifestPath) return null;

  const actions = parseManifest(manifestPath, warn);
  const content = generateManifestDts(actions);
  const outPath = resolve(root, "src/streamdeck-env.d.ts");
  const written = writeManifestDtsIfChanged(outPath, content);

  return { manifestPath, written };
}
