import type { ExamplePreset, ScaffoldOptions } from "../templates.js";
import { createAdapterFiles, createPluginEntrypoint } from "./shared.js";

// ── Basic Pack Example ──────────────────────────────────────────────
//
// Five actions demonstrating a range of Stream Deck features:
//   - Counter key (useState + key events)
//   - Timer key (useInterval + toggle)
//   - Toggle key (useSettings + persisted state)
//   - Volume dial (encoder events + ProgressBar component)
//   - Equalizer TouchStrip (useTick animation + dial/tap controls)

function createCounterAction(pluginUuid: string): string {
  return [
    'import { useState } from "react";',
    'import { defineAction, useKeyDown, useKeyUp, tw } from "@fcannizzaro/streamdeck-react";',
    "",
    "function CounterKey() {",
    "  const [count, setCount] = useState(0);",
    "  const [pressed, setPressed] = useState(false);",
    "",
    "  useKeyDown(() => {",
    "    setCount((value) => value + 1);",
    "    setPressed(true);",
    "  });",
    "",
    "  useKeyUp(() => {",
    "    setPressed(false);",
    "  });",
    "",
    "  return (",
    "    <div",
    "      className={tw(",
    '        "flex h-full w-full flex-col items-center justify-center gap-1",',
    '        pressed ? "bg-linear-to-br from-[#2563eb] to-[#1d4ed8]" : "bg-linear-to-br from-[#0f172a] to-[#1e293b]",',
    "      )}",
    "    >",
    '      <span className="text-[12px] font-semibold uppercase tracking-[0.2em] text-white/70">',
    "        Count",
    "      </span>",
    '      <span className="text-[34px] font-black text-white">{count}</span>',
    "    </div>",
    "  );",
    "}",
    "",
    "export const counterAction = defineAction({",
    `  uuid: "${pluginUuid}.counter",`,
    "  key: CounterKey,",
    "  info: {",
    '    name: "Counter",',
    '    icon: "imgs/actions/counter",',
    "  },",
    "});",
    "",
  ].join("\n");
}

function createTimerAction(pluginUuid: string): string {
  return [
    'import { useCallback, useState } from "react";',
    'import { defineAction, useInterval, useKeyDown, tw } from "@fcannizzaro/streamdeck-react";',
    "",
    "function TimerKey() {",
    "  const [elapsed, setElapsed] = useState(0);",
    "  const [running, setRunning] = useState(false);",
    "",
    "  useKeyDown(() => {",
    "    setRunning((value) => !value);",
    "  });",
    "",
    "  useInterval(() => {",
    "    setElapsed((value) => value + 100);",
    "  }, running ? 100 : null);",
    "",
    "  const formatTime = useCallback((ms: number) => {",
    "    const seconds = Math.floor(ms / 1000);",
    "    const minutes = Math.floor(seconds / 60);",
    "    const displaySeconds = seconds % 60;",
    "    const tenths = Math.floor((ms % 1000) / 100);",
    '    return `${minutes}:${String(displaySeconds).padStart(2, "0")}.${tenths}`;',
    "  }, []);",
    "",
    "  return (",
    "    <div",
    "      className={tw(",
    '        "flex h-full w-full flex-col items-center justify-center gap-1",',
    '        running ? "bg-[#1b5e20]" : "bg-[#212121]",',
    "      )}",
    "    >",
    '      <span className="text-[10px] font-medium text-white/60">{running ? "RUNNING" : "STOPPED"}</span>',
    '      <span className="text-[22px] font-bold text-white">{formatTime(elapsed)}</span>',
    "    </div>",
    "  );",
    "}",
    "",
    "export const timerAction = defineAction({",
    `  uuid: "${pluginUuid}.timer",`,
    "  key: TimerKey,",
    "  info: {",
    '    name: "Timer",',
    '    icon: "imgs/actions/timer",',
    "  },",
    "});",
    "",
  ].join("\n");
}

function createToggleAction(pluginUuid: string): string {
  return [
    'import { defineAction, useKeyDown, useSettings, tw } from "@fcannizzaro/streamdeck-react";',
    "",
    "type ToggleSettings = {",
    '  mode: "off" | "auto" | "on";',
    "};",
    "",
    'const modes = ["off", "auto", "on"] as const;',
    'const modeColors = { off: "#b71c1c", auto: "#f57f17", on: "#1b5e20" };',
    'const modeLabels = { off: "OFF", auto: "AUTO", on: "ON" };',
    "",
    "function ToggleKey() {",
    "  const [settings, setSettings] = useSettings<ToggleSettings>();",
    '  const mode = settings.mode ?? "off";',
    "",
    "  useKeyDown(() => {",
    "    const currentIndex = modes.indexOf(mode);",
    "    const nextMode = modes[(currentIndex + 1) % modes.length] ?? modes[0];",
    "    setSettings({ mode: nextMode });",
    "  });",
    "",
    "  return (",
    "    <div",
    "      className={tw(",
    '        "flex h-full w-full flex-col items-center justify-center gap-1.5",',
    "        `bg-[${modeColors[mode]}]`,",
    "      )}",
    "    >",
    '      <div className="flex flex-row gap-1.5">',
    "        {modes.map((value) => (",
    "          <div",
    "            key={value}",
    "            className={tw(",
    '              "h-2 w-2 rounded-full",',
    '              value === mode ? "bg-white" : "bg-white/30",',
    "            )}",
    "          />",
    "        ))}",
    "      </div>",
    '      <span className="text-[20px] font-bold text-white">{modeLabels[mode]}</span>',
    "    </div>",
    "  );",
    "}",
    "",
    "export const toggleAction = defineAction<ToggleSettings>({",
    `  uuid: "${pluginUuid}.toggle",`,
    "  key: ToggleKey,",
    '  defaultSettings: { mode: "off" },',
    "  info: {",
    '    name: "Toggle",',
    '    icon: "imgs/actions/toggle",',
    "  },",
    "});",
    "",
  ].join("\n");
}

function createVolumeAction(pluginUuid: string): string {
  return [
    'import { useState } from "react";',
    'import { ProgressBar, defineAction, tw, useDialDown, useDialHint, useDialRotate } from "@fcannizzaro/streamdeck-react";',
    "",
    "function VolumeDial() {",
    "  const [volume, setVolume] = useState(50);",
    "  const [muted, setMuted] = useState(false);",
    "",
    "  useDialHint({",
    '    rotate: "Adjust volume",',
    '    press: muted ? "Unmute" : "Mute",',
    "  });",
    "",
    "  useDialRotate(({ ticks }) => {",
    "    if (!muted) {",
    "      setVolume((value) => Math.max(0, Math.min(100, value + ticks * 2)));",
    "    }",
    "  });",
    "",
    "  useDialDown(() => {",
    "    setMuted((value) => !value);",
    "  });",
    "",
    "  return (",
    "    <div",
    "      className={tw(",
    '        "flex h-full w-full flex-col items-center justify-center gap-4 p-2",',
    '        muted ? "bg-[#4a0000]" : "bg-[#1a1a1a]",',
    "      )}",
    "    >",
    '      <span className={tw("text-[24px] font-bold", muted ? "text-[#ff4444]" : "text-white")}>',
    '        {muted ? "MUTE" : `${volume}%`}',
    "      </span>",
    "      <ProgressBar",
    "        value={muted ? 0 : volume}",
    "        height={4}",
    '        color={muted ? "#ff4444" : "#4caf50"}',
    '        background="#333"',
    "        borderRadius={2}",
    "      />",
    "    </div>",
    "  );",
    "}",
    "",
    "export const volumeAction = defineAction({",
    `  uuid: "${pluginUuid}.volume",`,
    "  dial: VolumeDial,",
    "  info: {",
    '    name: "Volume",',
    '    icon: "imgs/actions/volume",',
    "    encoder: {",
    '      layout: "$A0",',
    "      triggerDescription: {",
    '        rotate: "Adjust volume",',
    '        push: "Mute / Unmute",',
    "      },",
    "    },",
    "  },",
    "});",
    "",
  ].join("\n");
}

function createEqualizerAction(pluginUuid: string): string {
  return [
    'import { useState, useRef } from "react";',
    "import {",
    "  defineAction,",
    "  useTouchStrip,",
    "  useTouchStripDialRotate,",
    "  useTouchStripDialDown,",
    "  useTouchStripTap,",
    "  useTick,",
    '} from "@fcannizzaro/streamdeck-react";',
    "",
    "const BAR_COUNT = 32;",
    "const BAR_GAP = 3;",
    "const MIN_SPEED = 0.2;",
    "const MAX_SPEED = 5;",
    "const DEFAULT_SPEED = 1;",
    "const DEFAULT_AMPLITUDE = 0.8;",
    "",
    "const THEMES = [",
    '  { from: "#667eea", to: "#764ba2" },',
    '  { from: "#00ff88", to: "#00aa55" },',
    '  { from: "#ff3366", to: "#ff9966" },',
    '  { from: "#00bcd4", to: "#2196f3" },',
    '  { from: "#ffd700", to: "#ff8c00" },',
    "] as const;",
    "",
    "function lerpColor(a: string, b: string, t: number): string {",
    "  const parseHex = (hex: string) => {",
    '    const h = hex.replace("#", "");',
    "    return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];",
    "  };",
    "  const [ar, ag, ab] = parseHex(a);",
    "  const [br, bg, bb] = parseHex(b);",
    "  const r = Math.round(ar! + (br! - ar!) * t);",
    "  const g = Math.round(ag! + (bg! - ag!) * t);",
    "  const blue = Math.round(ab! + (bb! - ab!) * t);",
    "  return `rgb(${r},${g},${blue})`;",
    "}",
    "",
    "function EqualizerTouchStrip() {",
    "  const { width, height, segmentWidth } = useTouchStrip();",
    "",
    "  const [speed, setSpeed] = useState(DEFAULT_SPEED);",
    "  const [amplitude, setAmplitude] = useState(DEFAULT_AMPLITUDE);",
    "  const [paused, setPaused] = useState(false);",
    "  const [themeIndex, setThemeIndex] = useState(0);",
    "  const timeRef = useRef(0);",
    "  const [time, setTime] = useState(0);",
    "",
    "  const theme = THEMES[themeIndex % THEMES.length]!;",
    "  const barWidth = (width - BAR_GAP * (BAR_COUNT + 1)) / BAR_COUNT;",
    "",
    "  useTick((delta) => {",
    "    if (paused) return;",
    "    timeRef.current += delta * 0.001 * speed;",
    "    setTime(timeRef.current);",
    "  });",
    "",
    "  useTouchStripDialRotate(({ column, ticks }) => {",
    "    if (column === 0) {",
    "      setSpeed((s) => Math.max(MIN_SPEED, Math.min(MAX_SPEED, s + ticks * 0.2)));",
    "    } else if (column === 1) {",
    "      setAmplitude((a) => Math.max(0.1, Math.min(1, a + ticks * 0.05)));",
    "    }",
    "  });",
    "",
    "  useTouchStripDialDown(({ column }) => {",
    "    if (column === 2) {",
    "      setPaused((p) => !p);",
    "    } else if (column === 3) {",
    "      setSpeed(DEFAULT_SPEED);",
    "      setAmplitude(DEFAULT_AMPLITUDE);",
    "      setPaused(false);",
    "      timeRef.current = 0;",
    "      setTime(0);",
    "    }",
    "  });",
    "",
    "  useTouchStripTap(() => {",
    "    setThemeIndex((i) => (i + 1) % THEMES.length);",
    "  });",
    "",
    "  return (",
    "    <div",
    "      style={{",
    "        width,",
    "        height,",
    '        position: "relative",',
    '        overflow: "hidden",',
    '        background: "#0d1117",',
    "      }}",
    "    >",
    "      {Array.from({ length: BAR_COUNT }, (_, i) => {",
    "        const phase = (i / BAR_COUNT) * Math.PI * 4;",
    "        const wave1 = Math.sin(time * 2 + phase) * 0.5 + 0.5;",
    "        const wave2 = Math.sin(time * 3.7 + phase * 0.6) * 0.3 + 0.3;",
    "        const value = Math.min(1, (wave1 + wave2) * amplitude);",
    "        const barHeight = Math.max(2, value * (height - 10));",
    "        const x = BAR_GAP + i * (barWidth + BAR_GAP);",
    "        const color = lerpColor(theme.from, theme.to, i / BAR_COUNT);",
    "",
    "        return (",
    "          <div",
    "            key={i}",
    "            style={{",
    '              position: "absolute",',
    "              left: x,",
    "              bottom: 5,",
    "              width: barWidth,",
    "              height: barHeight,",
    "              background: color,",
    "              borderRadius: 2,",
    "            }}",
    "          />",
    "        );",
    "      })}",
    "      {[0, 1, 2, 3].map((col) => (",
    "        <div",
    "          key={`label-${col}`}",
    "          style={{",
    '            position: "absolute",',
    "            left: col * segmentWidth,",
    "            top: 4,",
    "            width: segmentWidth,",
    '            display: "flex",',
    '            alignItems: "center",',
    '            justifyContent: "center",',
    "          }}",
    "        >",
    "          <span",
    "            style={{",
    '              color: "white",',
    "              fontSize: 10,",
    '              fontFamily: "Inter",',
    "              opacity: 0.4,",
    "            }}",
    "          >",
    "            {col === 0",
    "              ? `SPD ${speed.toFixed(1)}x`",
    "              : col === 1",
    "                ? `AMP ${Math.round(amplitude * 100)}%`",
    "                : col === 2",
    "                  ? paused",
    '                    ? "RESUME"',
    '                    : "PAUSE"',
    '                  : "RESET"}',
    "          </span>",
    "        </div>",
    "      ))}",
    "    </div>",
    "  );",
    "}",
    "",
    "export const equalizerAction = defineAction({",
    `  uuid: "${pluginUuid}.equalizer",`,
    "  touchStrip: EqualizerTouchStrip,",
    "  info: {",
    '    name: "Equalizer",',
    '    icon: "imgs/actions/equalizer",',
    "    encoder: {",
    '      layout: "layouts/touchstrip.json",',
    "      triggerDescription: {",
    '        rotate: "Adjust speed / amplitude",',
    '        push: "Pause / Reset",',
    '        touch: "Change color theme",',
    "      },",
    "    },",
    "  },",
    "});",
    "",
  ].join("\n");
}

function createTouchStripLayout(): string {
  return `${JSON.stringify(
    {
      id: "com.streamdeck-react.touchstrip-layout",
      items: [
        {
          key: "canvas",
          type: "pixmap",
          rect: [0, 0, 200, 100],
        },
      ],
    },
    null,
    2,
  )}\n`;
}

export function basicPreset(): ExamplePreset {
  return {
    dependencies: {},
    actions: [
      { id: "counter", name: "Counter", colors: { from: "#2563eb", to: "#1d4ed8" } },
      { id: "timer", name: "Timer", colors: { from: "#1b5e20", to: "#212121" } },
      { id: "toggle", name: "Toggle", colors: { from: "#f57f17", to: "#b71c1c" } },
      { id: "volume", name: "Volume", colors: { from: "#1a1a1a", to: "#4a0000" } },
      { id: "equalizer", name: "Equalizer", colors: { from: "#667eea", to: "#764ba2" } },
    ],
    files: (options: ScaffoldOptions) => ({
      "src/actions/counter.tsx": createCounterAction(options.pluginUuid),
      "src/actions/timer.tsx": createTimerAction(options.pluginUuid),
      "src/actions/toggle.tsx": createToggleAction(options.pluginUuid),
      "src/actions/volume.tsx": createVolumeAction(options.pluginUuid),
      "src/actions/equalizer.tsx": createEqualizerAction(options.pluginUuid),
      [`${options.pluginUuid}.sdPlugin/layouts/touchstrip.json`]: createTouchStripLayout(),
      ...createAdapterFiles(options.adapter),
      "src/plugin.ts": createPluginEntrypoint(
        ["counterAction", "timerAction", "toggleAction", "volumeAction", "equalizerAction"],
        undefined,
        options.adapter,
      ),
    }),
  };
}
