import type { ExamplePreset, ScaffoldOptions } from "../templates.js";
import { createAdapterFiles, createPluginEntrypoint } from "./shared.js";

// ── Pokemon Example ─────────────────────────────────────────────────
//
// Data fetching with TanStack Query — loads remote Pokemon sprites on
// key press.  Demonstrates useQuery, data URIs, loading/error states,
// and a QueryClientProvider wrapper.

function createQueryWrapper(): string {
  return [
    'import type { ReactNode } from "react";',
    'import { QueryClient, QueryClientProvider } from "@tanstack/react-query";',
    "",
    "const queryClient = new QueryClient({",
    "  defaultOptions: {",
    "    queries: {",
    "      retry: 2,",
    "      staleTime: Infinity,",
    "    },",
    "  },",
    "});",
    "",
    "type QueryWrapperProps = {",
    "  children?: ReactNode;",
    "};",
    "",
    "export function QueryWrapper({ children }: QueryWrapperProps) {",
    "  return <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>;",
    "}",
    "",
  ].join("\n");
}

function createPokemonAction(pluginUuid: string): string {
  return [
    'import { useState } from "react";',
    'import { useQuery } from "@tanstack/react-query";',
    'import { Image, defineAction, tw, useKeyDown } from "@fcannizzaro/streamdeck-react";',
    "",
    "const MAX_POKEMON_ID = 1025;",
    "",
    "function randomPokemonId(): number {",
    "  return Math.floor(Math.random() * MAX_POKEMON_ID) + 1;",
    "}",
    "",
    "function capitalize(value: string): string {",
    "  return value.charAt(0).toUpperCase() + value.slice(1);",
    "}",
    "",
    "function padId(id: number): string {",
    '  return `#${String(id).padStart(3, "0")}`;',
    "}",
    "",
    "async function bufferToDataUri(response: Response, mime: string): Promise<string> {",
    "  const arrayBuffer = await response.arrayBuffer();",
    '  const base64 = Buffer.from(arrayBuffer).toString("base64");',
    "  return `data:${mime};base64,${base64}`;",
    "}",
    "",
    "type PokemonData = {",
    "  id: number;",
    "  name: string;",
    "  spriteDataUri: string;",
    "};",
    "",
    "async function fetchPokemon(id: number, signal: AbortSignal): Promise<PokemonData> {",
    "  const response = await fetch(`https://pokeapi.co/api/v2/pokemon/${id}`, { signal });",
    "",
    "  if (!response.ok) {",
    "    throw new Error(`PokeAPI returned ${response.status}`);",
    "  }",
    "",
    "  const payload = (await response.json()) as {",
    "    name: string;",
    "    sprites: {",
    "      front_default: string | null;",
    '      other?: { "official-artwork"?: { front_default: string | null } };',
    "    };",
    "  };",
    "",
    "  const spriteUrl =",
    "    payload.sprites.front_default ??",
    '    payload.sprites.other?.["official-artwork"]?.front_default ??',
    "    null;",
    "",
    "  if (!spriteUrl) {",
    "    throw new Error(`No sprite available for Pokemon ${id}`);",
    "  }",
    "",
    "  const spriteResponse = await fetch(spriteUrl, { signal });",
    "",
    "  if (!spriteResponse.ok) {",
    "    throw new Error(`Sprite fetch returned ${spriteResponse.status}`);",
    "  }",
    "",
    '  const spriteDataUri = await bufferToDataUri(spriteResponse, "image/png");',
    "  return { id, name: payload.name, spriteDataUri };",
    "}",
    "",
    "function PokemonKey() {",
    "  const [pokemonId, setPokemonId] = useState(() => randomPokemonId());",
    "",
    "  useKeyDown(() => {",
    "    setPokemonId(randomPokemonId());",
    "  });",
    "",
    "  const { data, isLoading, isError } = useQuery({",
    '    queryKey: ["pokemon", pokemonId],',
    "    queryFn: ({ signal }) => fetchPokemon(pokemonId, signal),",
    "  });",
    "",
    "  if (isLoading) {",
    "    return (",
    "      <div",
    "        className={tw(",
    '          "flex h-full w-full flex-col items-center justify-center",',
    '          "bg-gradient-to-br from-[#1a1a2e] to-[#16213e]",',
    "        )}",
    "      >",
    '        <span className="text-[14px] font-bold text-white/80">Loading...</span>',
    "      </div>",
    "    );",
    "  }",
    "",
    "  if (isError || !data) {",
    "    return (",
    "      <div",
    "        className={tw(",
    '          "flex h-full w-full flex-col items-center justify-center gap-1",',
    '          "bg-gradient-to-br from-[#4a0000] to-[#1a0000]",',
    "        )}",
    "      >",
    '        <span className="text-[12px] font-bold text-[#ff6b6b]">Error</span>',
    '        <span className="text-[10px] text-white/50">{padId(pokemonId)}</span>',
    "      </div>",
    "    );",
    "  }",
    "",
    "  return (",
    "    <div",
    "      className={tw(",
    '        "relative h-full w-full overflow-hidden",',
    '        "bg-gradient-to-br from-[#0f3460] to-[#533483]",',
    "      )}",
    "    >",
    '      <div className={tw("absolute inset-0 flex items-center justify-center")}>',
    '        <Image src={data.spriteDataUri} width={144} height={144} fit="contain" />',
    "      </div>",
    '      <div className={tw("relative z-10 flex h-full w-full items-end justify-center px-2 pb-2")}>',
    "        <span",
    '          className="text-[16px] font-bold text-white"',
    '          style={{ textShadow: "0 3px 8px rgba(0, 0, 0, 0.9)" }}',
    "        >",
    "          {capitalize(data.name)}",
    "        </span>",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    "",
    "export const pokemonAction = defineAction({",
    `  uuid: "${pluginUuid}.pokemon",`,
    "  key: PokemonKey,",
    "  info: {",
    '    name: "Random Pokemon",',
    '    icon: "imgs/actions/pokemon",',
    "  },",
    "});",
    "",
  ].join("\n");
}

export function pokemonPreset(): ExamplePreset {
  return {
    dependencies: {
      "@tanstack/react-query": "^5.72.2",
    },
    actions: [
      { id: "pokemon", name: "Random Pokemon", colors: { from: "#0f3460", to: "#533483" } },
    ],
    files: (options: ScaffoldOptions) => ({
      "src/actions/pokemon.tsx": createPokemonAction(options.pluginUuid),
      "src/wrapper.tsx": createQueryWrapper(),
      ...createAdapterFiles(options.adapter),
      "src/plugin.ts": createPluginEntrypoint(["pokemonAction"], "QueryWrapper", options.adapter),
    }),
  };
}
